#!/usr/bin/env bash

RED='\033[0;31m'
RESET='\033[0m'
set -eou pipefail

# SAVE OPTION
#wall=cyberpunk

#WALL_DIR=/home/roe/pix/sara
#WALL_DIR=/home/roe/pix/walls
WALL_DIR=/home/roe/pix/walls/alex_steven_martin
#WALL_DIR=/home/roe/pix/alex_steven_martin

THEMES_DIR=/home/roe/skps/custom_walz

random_flag=0
if [[ $# -eq 1 && $1 == "-r" ]]; then
  random_flag=1
else
  random_flag=0
fi

# Prioritize command-line arg
#if  [[ $# -eq 1 ]]; then
if  [[ $# -eq 1 && $1 != "-r" ]]; then
  wall=$1
  node_name=$1
# If no save, randomize
#elif [ -z ${wall+x} ]; then
elif [ -z ${wall+x} ] || [ "$random_flag" -eq 1 ]; then
  node_name=$(ls -1 $WALL_DIR | shuf -n 1)
  wall=$WALL_DIR/$node_name
# Else execute save
else
  node_name=$wall
  wall=$WALL_DIR/$wall
fi

# Add this as background wallpaper
xwallpaper --zoom $wall

# Clear
wal -c

echo -e "${RED}newlook: $node_name${RESET}"
echo -e "${RED}newlook: searching: $node_name.json${RESET}"

if [[ -f "$THEMES_DIR/$node_name.json" ]]; then
  echo -e "${RED}newlook: custom theme file found${RESET}"
else
  echo -e "${RED}nelook: custom theme file not found${RESET}"
fi

if wal -a 92 -f "$THEMES_DIR/$node_name.json"; then
  echo -e "${RED}newlook: applied custom theme${RESET}"
else
  wal -a 92 -i $wall
  echo -e "${RED}newlook: using wal-generated theme${RESET}"
fi

nohup bash -c "/home/roe/.config/polybar/bar.sh" 2>&1 > /dev/null &
cp /home/roe/.cache/wal/colors-wal-dmenu.h /home/roe/git/suckless-sara/dmenu
cd /home/roe/git/suckless-sara/dmenu
make
make clean
